### PR TITLE
Colorize ORM class names

### PR DESCRIPTION
**Pull request by ixti**
Second attempt on #220

### CODE REVIEW

**Comment by ixti** [comment]
Hm. Seems like this PR will need some work in order to fix it :D

**Comment by ixti** [comment]
Seems like issue with `ActiveRecord.inspect`. Will check this later today or over the week.

**Comment by gerrywastaken** [comment]
No worries, feel free to work on it as long as needed.

**Comment by ixti** [comment]
@gerrywastaken ready for review

**Comment by ixti** [comment]
@gerrywastaken ping

**Comment by ixti** [comment]
@gerrywastaken if there's no interest in this PR, please close it.

**Pull request merged**
