### PR TITLE
include add files under spec/ in built gem

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
The background of this change is that Debian packages of Rubygems should run thier tests after building to find problems, so having everything available what's needed for the tests to run is crucial.

**Comment by gerrywastaken** [comment]
@mmoll I think that was an accidental omission. Thanks for the fix and sorry about the wait. Thanks for helping our gem play nicely with Debian.

For posterity, can you point to any docs explaining this requirement on Debian or any link related to it?

**Comment by mmoll** [comment]
@gerrywastaken thanks for accepting! https://wiki.debian.org/Teams/Ruby/Packaging/Tests is the closest I found, although the reasoning is not 100% explained. It's mainly just about making sure that the specific version combination of the gems packaged in one Debian distribution play nice with each other.

**Comment by gerrywastaken** [comment]
@mmoll Thanks for the doc and the PR. :)

**Comment by gerrywastaken** [comment]
Quoting the relevant part for posterity:

> Case four: missing test folder from rubygems org
> 
> Sometimes, gems are not packaged with their test folders. Often, these are present at upstream, e.g., at github.
> 
> Download the tarball from the upstream source (you may need to convert it to .tar.gz yourself), then run dh-make-ruby <gem-name>.tar.gz."

I can see how that would be an annoyance.

**Pull request merged**
