### PR TITLE
Update copyright header

### PR DESCRIPTION
**Pull request by waldyr**
https://github.com/awesome-print/awesome_print/pull/242#issuecomment-224172218

### CODE REVIEW

**Comment by gerrywastaken** [comment]
Relevant link for anybody wondering about this change: https://github.com/awesome-print/awesome_print/pull/242#issuecomment-224172218

@waldyr any chance of adding this to the commit message body?

**Comment by gerrywastaken** [comment]
Cheers @waldyr. Any chance of putting this link in the commit message body and and quoting the comment?

I know it might seem like overkill, but I'm just thinking about the possibility of something happening to Github and then that history getting lost. Just thinking of Sourceforge and Google Code.

**Comment by waldyr** [comment]
Sure! I'll do it.

**Comment by gerrywastaken** [comment]
LGTM

**Pull request merged**
