### PR TITLE
Remove copyright header

### PR DESCRIPTION
**Pull request by waldyr**
Taken from `mg-v2`. @gerrywastaken what do you think?

### CODE REVIEW

**Comment by gerrywastaken** [comment]
@waldyr I understand where you are coming from. I personally believe the license file already demonstrates copyright. Also in cases where copyright is not clear, as far as I understand, the copyright automatically belongs to the creator of the change. But I'm not a lawyer, so I may be wrong.

**However**, @michaeldv has made a strong objection to these changes, so I think the right thing to do would be to leave it in:

> Fourth, you can add your own copyright but don't remove somebody else's. You just don't.
https://github.com/awesome-print/awesome_print/pull/193#issuecomment-83710204

I agree about updating the date, but just to be cautious I'd like some input from @michaeldv before even modifying that.

Just my opinion.

**Comment by waldyr** [comment]
@gerrywastaken Your opinion means a lot to me. As I was breaking up `mg-v2` branch I unfortunately brought up the same discussion. Sorry for that 😞 . 

Let's see what @michaeldv have to say about this. I'm fine with any conclusion.

**Comment by gerrywastaken** [comment]
@waldyr All is good, there is nothing wrong with revisiting discussions. I greatly appreciate you breaking up `mg-v2` as there is no way it could be merged in one go. I wouldn't be surprised if this was a huge stumbling block for the release of v2. One of the reasons I'm intrigued by the Linux approach of making major version bumps, just another commit instead of a huge set of carefully coordinated changes. https://github.com/torvalds/linux/commit/02f8c6aee8df3cdc935e9bdd4f2d020306035dbe

**Comment by michaeldv** [comment]
I would much prefer **not** to remove copyright notices but I would change them everywhere to:

    Copyright (c) 2010-2016 Michael Dvorkin and contributors.

**Comment by gerrywastaken** [comment]
@waldyr If you wish to make the change suggested by @michaeldv, please make sure to quote and link to his comment in the commit message body, so that it's clear that the change his approval. Just so that anybody going through the changes can follow along.

**Pull request closed without merging**
