### PR TITLE
Color hash keys (w/ specs)

### PR DESCRIPTION
**Pull request by steakknife**
Supersedes #58

### CODE REVIEW

**Comment by gerrywastaken** [comment]
While testing your PR I ran into a bug that had previously slipped through. Fixed here:
https://github.com/awesome-print/awesome_print/pull/267

However your change means that code will once again not work correctly as it expects a symbol to begin with a colon. If plain_single_line starts adding color strings, then `symbol?` no longer will return true which will break the ruby19_syntax option. There's probably a really easy way to fix all this, but I can't think of it right now.

Also the name plain_single_line suggests `options[:plain] = true` and `options[:multiline] = false`. If we want a method that just does a `options[:multiline] = false` then perhaps it's better to create a new method that does only that and call it `single_line` leaving `plain_single_line` unmodified.

What are your thoughts?

**Comment by steakknife** [comment]
This was a quick hack to highlight an issue. Whichever way forward colorizes / formats keys of hashes by default. Leaving this open as a reminder would probably be good to prevent falling between the cracks.

**Comment by steakknife** [comment]
cc @gerrywastaken

**Comment by gerrywastaken** [comment]
@steakknife That's fine with me. I've got a few things on my plate at the moment, but I also like the idea behind this PR, so I'll come back to it, but it might not be soon. Thanks for the insight btw.

**Pull request closed without merging**
